name: bolsa_millonaria
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - plotly
  - jinja2
  - pip
  - pip:
      - streamlit>=1.32
      - yfinance>=0.2.54
